#!/bin/sh

echo "1) audit code with pylint-spaces.conf file"
echo "2) audit code with pylint-tabs.conf file"

echo "Choice:" 
read choice

case $choice in
1) pylint ../gummi/*.py --rcfile=./pylint-spaces.conf;;
2) pylint ../gummi/*.py --rcfile=./pylint-tabs.conf;;
esac

