#!/bin/bash
# Gummi build script for Ubuntu 9.04 Jaunty
# Alexander van der Mey - 8 October 2009
# Version: 0.1

# This script isn't very intelligent and might not run on your system 
# with your setup or directory paths, so leave the packaging to me ;)

echo "fetching the sourcecode.."
svn co http://midnightcoding.org/svn/gummi/trunk/ gummi-read-only

cd gummi-read-only

rm po/template*.po
rename 's/(.*)-[0-9]*/$1/g' po/*.po

echo "What's the version number for this release?"

read rlschoice

sed -i s/S.E.D/$rlschoice/ setup.py
sed -i s/svn/$rlschoice/ gummi/Preferences.py

python setup.py sdist

cp ./dist/gummi-$rlschoice.tar.gz ../
cd ..
rm -rf gummi-read-only

mv gummi-$rlschoice.tar.gz gummi_$rlschoice.orig.tar.gz

export DEBFULLNAME="Alexander van der Mey"
export DEBEMAIL="alexvandermey@gmail.com"

tar -xf gummi_$rlschoice.orig.tar.gz
cd gummi-$rlschoice

dh_make -s -b
cd debian
rm *ex *EX
rm README.Debian dirs
dch -e
cp ../../control ./
cp ../../rules ./



MIT='
    Copyright (c) 2009 Alexander van der Mey <alexvandermey@gmail.com>\n

    Permission is hereby granted, free of charge, to any person obtaining a copy\n
    of this software and associated documentation files (the "Software"), to deal\n
    in the Software without restriction, including without limitation the rights\n
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n
    copies of the Software, and to permit persons to whom the Software is\n
    furnished to do so, subject to the following conditions:\n
\n
    The above copyright notice and this permission notice shall be included in\n
    all copies or substantial portions of the Software.\n
\n
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n
    THE SOFTWARE.\n
\n
The Debian packaging is copyright 2009, gummi <alexvandermey@gmail.com> and\n
is licensed under the GPL, see `/usr/share/common-licenses/GPL\n
'

sed -i s/gummi@unknown/alexvandermey@gmail.com/ copyright
sed -i s@url://example.com@http://gummi.midnightcoding.org/@ copyright
sed -i s/"put author's name and email here"/"Alexander van der Mey <alexvandermey@gmail.com>"/ copyright
sed -i s/"Copyright (C) YYYY Name OfAuthor"/"Alexander van der Mey <alexvandermey@gmail.com>"/ copyright
sed -i '16,24d' copyright
echo $MIT >> copyright

sed -i s/nnnn/314159265358/ changelog
sed -i s/unstable/jaunty/ changelog
sed -i s/"<nnnn is the bug number of your ITP>"/""/ changelog
sed -i s/"gummi <gummi@unknown>"/"Alexander van der Mey <alexvandermey@gmail.com>"/ changelog
sed -i s/$rlschoice"-1"/$rlschoice"-0ubuntu1"/ changelog

sed -i s/S.E.D/$rlschoice/ control

cd ..

if [ "$1" == "deb" ]; then
  dpkg-buildpackage -rfakeroot
elif [ "$1" == "ppa" ]; then
  debuild -S
fi
