#!/bin/bash
# Gummi win32 build script
# by Wei-Ning Huang
#
# You need to run this script under MSYS.
#
# Depends: MSYS, NSIS, python, Gummi dependencies.
#

wd=`pwd`

dest=build.win32
mkdir $dest
cp -r ../gummi $dest
cp -r ../po $dest
cp win32/Installer.nsi win32/setup.py $dest/gummi
cp $dest/gummi/docs/LICENSE $dest/gummi

# Manage translations
cd $dest/po
rm template*.po

for i in `ls *.po`; do
  mv $i ${i%-*}.po
done

for i in `ls *.po`; do
  msgfmt $i -o ${i%.po}.mo
done

# Manage version
cd ../gummi
echo "What's the version number for this release?"
read rlschoice

# sed in MSYS may be out of date and does not support the -i option, get latest
# version from http://gnuwin32.sourceforge.net/packages/sed.htm
sed -i s/svn/$rlschoice/ setup.py
sed -i s/svn/$rlschoice/ Installer.nsi
sed -i s/svn/$rlschoice/ Preferences.py

# Copy py2exe related files
mv misc/gummi gummi.py
mv misc/gummi_256x256.ico .
mv misc/gummi_64x64.ico .

# run py2exe
python setup.py py2exe -p atk,gio,pango,pangocairo,cairo,poppler,gtksourceview2

# Remove DLLs copied by py2exe becasue py2exe copies Win7 specific DLLs and
# cause DLL laod failed on WinXP
rm -f `ls dist/*.dll dist/*.DLL | grep -v 'python26.dll'`

# Copy gtk DLLs, settings
cp -r $wd/win32/GtkSettings/* $wd/win32/DLLs/*.dll dist

# Copy locales
cd $wd/$dest/po

for i in `ls *.mo`; do
  echo "copying $i ..."
  mos=../gummi/dist/share/locale/${i%.mo}/LC_MESSAGES
  mkdir -p $mos
  cp $i $mos
done

# Make Installer
cd ../gummi
rm -rf `find -name .svn`
makensis Installer.nsi
mv Gummi-$rlschoice-setup.exe $wd
