#!/bin/bash

export DEBFULLNAME="Wei-Ning Huang (AZ)"
export DEBEMAIL="aitjcize@gmail.com"

notex=0

PKG_DIR=$HOME/Public
mkdir -p $PKG_DIR

owd=`pwd`
package=${owd##/*/}

if [ -n "$2" ] && [ "$2" == "notex" ]; then
    notex=1
fi

if [ -e configure.ac ]; then
  version=`sed -n 's/AC_INIT([^,]*, \[\([a-zA-Z0-9.~\-]*\)\], .*/\1/p' configure.ac`
elif [ -e setup.py ]; then
  version=`sed -n "s/.*version = '\(.*\)'.*/\1/p" setup.py`
fi

if [ "$1" == "clean" ]; then
  rm -rf $PKG_DIR/$package*
  exit 0
fi

echo "Package: $package"
echo "Version: $version"

cd ..
cp -r $package /tmp/$package-$version
rm -rf /tmp/$package-$version/dev
mv /tmp/$package-$version $PKG_DIR
cd $PKG_DIR

if [ "$1" == "sdist" ]; then
  tar -zcf ${package}-$version.tar.gz $package-$version
  exit 0
else
  tar -zcf ${package}_$version.orig.tar.gz $package-$version
fi


cd $package-$version

dh_make -s -b

cp $owd/dev/rules $owd/dev/control debian
cd debian

rm *.ex *.EX README.*

dch -e

if test 1 -eq $notex; then
    sed -i 's/Source: gummi/Source: gummi-notex/g' control
    sed -i 's/Package: gummi/Package: gummi-notex/g' control
    sed -i 's/, texlive, texlive-extra-utils, texlive-latex-extra//g' control
    sed -i 's/gummi/gummi-notex/g' changelog
    mv ../../${package}_$version.orig.tar.gz ../../${package}-notex_$version.orig.tar.gz
fi

cd ..

if [ "$1" == "deb" ] || [ -z "$1" ]; then
  dpkg-buildpackage -rfakeroot
elif [ "$1" == "ppa" ]; then
  debuild -S
fi
