[Icon Theme]
Name=elementary
Comment=Smooth modern theme designed to be intuitive.
Inherits=hicolor

Example=directory-x-normal

#Directory list
Directories=actions/22,actions/24,actions/32,actions/48,places/16,places/32,mimes/48,status/32,status/48,status/64

[actions/22]
Size=22
Context=Actions
Type=scalable

[actions/24]
Size=24
Context=Actions
Type=scalable

[actions/32]
Size=32
Context=Actions
Type=scalable

[actions/48]
Size=48
Context=Actions
Type=Scalable

[mimes/48]
Size=48
Context=MimeTypes
Type=Scalable

[places/16]
Size=16
Context=Places
Type=scalable

[places/32]
Size=32
Context=Places
Type=scalable

[status/32]
Size=32
Context=Status
Type=scalable

[status/48]
Size=48
Context=Status
Type=Scalable

[status/64]
Size=64
Context=Status
Type=Scalable
