.TH GUMMI 1 "JANUARY 2009" Linux "User Manuals"
.SH NAME
gummi \- LaTeX editor
.SH DESCRIPTION
.B gummi
is a simple LaTeX editor for GTK+
and PyGTK. 
.SH OPTIONS
No options available for now.
.SH BUGS
Undoubtedly, please report at: 
http://gummi.midnightcoding.org
.SH AUTHOR
Alexander van der Mey <alexvandermey@gmail.com>

