.TH GUMMI 1 "APRIL 2011" Linux "User Manuals"
.SH NAME
gummi \- LaTeX editor
.SH DESCRIPTION
.B gummi
is a simple LaTeX editor for GTK+.
.SH OPTIONS
.TP
\-d
run gummi with debug logging enabled.
.TP
\-h
display command line options.
.SH BUGS
Undoubtedly, please report at:
https://github.com/alexandervdm/gummi
.SH AUTHORS
Alexander van der Meij <gummi{pleasenospam}vandermeij.tech>
.PP
Wei-Ning Huang <aitjcize{pleasenospam}gmail.com>
